pluginManagement {
    repositories {
        maven { url = "https://maven.neoforged.net/releases" }
        gradlePluginPortal()
    }
}

plugins {
    id 'net.neoforged.moddev.repositories' version '2.0.74'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = "kencraft"
