pluginManagement {
    repositories {
        maven { url = "https://maven.neoforged.net/releases" }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

rootProject.name = "kencraft"
