modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '${mod_description}'

[[mixins]]
config = "kencraft.mixins.json"

[[dependencies.kencraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.248,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kencraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
